# Generated by Django 2.2 on 2021-06-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_geeksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='todoapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todoapp_field', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GeeksModel',
        ),
    ]
